# Generated by Django 5.2.7 on 2025-10-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_expansion', models.CharField(max_length=150, verbose_name='Nombre de Expansión')),
                ('fecha_lanzamiento', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('total_cartas', models.IntegerField(help_text='Número total de cartas en esta expansión.', verbose_name='Total de Cartas en Set')),
                ('idioma', models.CharField(max_length=50, verbose_name='Idioma de las Cartas')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa (en venta)')),
            ],
            options={
                'verbose_name': 'Expansión',
                'verbose_name_plural': 'Expansiones',
                'ordering': ['-fecha_lanzamiento'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto/Carta')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo (e.g., Pokémon, Entrenador, Energía)')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img_productos/', verbose_name='Imagen del Producto')),
                ('expansion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='app_pokemon.expansion', verbose_name='Expansión')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
